---
## Workflow to create a new git tag if version.py variable version gets updated
name: release

permissions:
  contents: write # write permission is required to create a GitHub release

on:
  push:
    branches:
      - 'main'
    paths:
      - 'share/version.py'

jobs:

  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

    - uses: actions/checkout@v4

    - name: Get version number
      shell: bash
      run: |
        VERSION=$(awk '/version/ {print $3}' share/version.py | tr -d '"')
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Create tag
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/lambda-v' + ${{ env.VERSION }},
            sha: context.sha
          })
