name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  ci_matrix:
    strategy:
      fail-fast: false
      matrix:
        goal:
          - docker-coverage
          - docker-lint
          - license
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Cleanup some tools from the workers to fix no space left
      run: |-
        df -h
        sudo rm -rf /usr/local/lib/android &
        sudo rm -rf /usr/local/lib/heroku /usr/local/aws-cli /usr/share/apache-maven* /usr/share/apache2 /usr/share/php* /usr/share/dotnet /opt /usr/local/lib/node_modules &

    - uses: actions/checkout@v3

    - name: Run
      run: make ${{ matrix.goal }}

    - name: Store test results
      if: contains(matrix.goal, 'coverage') && (success() || failure())
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: '**/elastic-serverless-forwarder-junit.xml'

    - if: failure()
      name: debug errors
      run: |-
        df -h
