name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  license:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - run: make license

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - run: make docker-lint

  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Cleanup some tools from the workers to fix no space left
      run: |-
        df -h
        sudo rm -rf /usr/local/lib/android &
        sudo rm -rf /usr/local/lib/heroku /usr/local/aws-cli /usr/share/apache-maven* /usr/share/apache2 /usr/share/php* /usr/share/dotnet /opt /usr/local/lib/node_modules &

    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9' # As defined in tests/scripts/docker/run_tests.sh
        cache: 'pip'          # caching pip dependencies

    - run: pip install -r requirements-tests.txt
    - run: pip install -r requirements.txt
    - run: make coverage
      env:
        # See https://github.com/elastic/elastic-serverless-forwarder/pull/280#issuecomment-1461554126
        AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY

    - name: Store test results
      if: success() || failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: '**/elastic-serverless-forwarder-junit.xml'

    - name: Code Coverage Summary Report
      if: success() || failure()
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        format: 'markdown'
        output: 'both'

    - name: Write to Job Summary
      if: success() || failure()
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
