name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Lint
      run: make docker-lint

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Test
      run: make docker-coverage

    - name: Store test results
      if: success() || failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: '**/elastic-serverless-forwarder-junit.xml'

  license:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: license
      run: make license
